DEFAULT_BATCH_SIZE = 8
DEFAULT_OPTIMIZER = "adam"
DEFAULT_LOSS = "crossentropy"
DEFAULT_LEARNING_RATE = 3e-4
DEFAULT_HIDDEN_SIZE = 64
DEFAULT_MAX_EPOCHS = 500
DEFAULT_DEVICE = "cpu"
DEFAULT_IGNORE_WORDS = "?!.,"

RANDOM_STATE = 42
VAL_DATASET_SIZE = 0.2